# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: 80DEEA
          SLACK_USERNAME: Wave-PWA
          SLACK_TITLE: PR
          SLACK_ICON: https://waverfid.xyz/wp-content/uploads/2021/08/waveRFID-185.png
          MSG_MINIMAL: Ref, Event, Commit

      - name: Hello world action step
        id: hello
        uses: vishalgheravada/ssh-github-action@6
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
        env:
          a: 1
